spring:
  #  application:
  #    name: mall-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:gateway-config.yaml
server:
  port: 88